services:
  - type: web
    name: negociabot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: negociabot-secret-key-cameroun-2026
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: negociabot-db
          property: connectionString

databases:
  - name: negociabot-db
    plan: free